# Generated by Django 2.2.5 on 2021-10-14 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=30, null=True, verbose_name='설치장소')),
                ('section', models.CharField(max_length=30, null=True, verbose_name='구역')),
                ('sensor', models.CharField(max_length=30, null=True, verbose_name='센서')),
                ('value', models.FloatField(verbose_name='센서값')),
                ('regdate', models.DateTimeField(auto_now_add=True, null=True, verbose_name='등록일')),
            ],
        ),
    ]
