# Generated by Django 2.2.5 on 2021-10-14 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sensor',
        ),
    ]
